version: "3.9"

services:
  db:
    image: postgres:15
    container_name: jasho-db
    restart: always
    environment:
      POSTGRES_USER: jasho_user
      POSTGRES_PASSWORD: jasho_pass
      POSTGRES_DB: jasho_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: jasho-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://jasho_user:jasho_pass@db:5432/jasho_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
